# Generated by Django 4.0.5 on 2022-06-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_sentence_labeler', '0002_sentence_labeler'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceLabeler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('label_value', models.CharField(blank=True, max_length=100, null=True)),
                ('level_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentence_labeler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceLabelerTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('label_value', models.CharField(blank=True, max_length=100, null=True)),
                ('level_value', models.IntegerField(blank=True, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_sentence_labeler.cvlabelmapper')),
            ],
        ),
        migrations.DeleteModel(
            name='Sentence_Labeler',
        ),
    ]
